server:
  port:
    10080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        driverClassName: com.mysql.cj.jdbc.Driver
        username: admin
        password: KH6O25l4G2h4dyMwV9TA
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 10
            minimum-idle: 2
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update #validate
